# Generated by Django 6.0 on 2026-10-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_last_seen_conversation_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="client_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
